# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Dev build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#    - uses: actions/setup-python@v2
#      with:
#        python-version: '3.6'

    - name: Create Dev Build
      run: |
        mkdir MCDReforged-dev
        mv * MCDReforged-dev || true
        cd MCDReforged-dev
        rm -rf .git
        rm -f %name%.spec .gitignore make_release.bat logo_long.png
        mkdir server
        mkdir config
        cp doc/readme_cn.md .
        rm -f plugins/*
        rm -rf doc
        cd ..
        zip -r MCDReforged-dev.zip ./MCDReforged-dev

    - uses: actions/upload-artifact@v2
      with:
        name: MCDReforged dev build for ${{ github.sha }}
        path: MCDReforged-dev.zip
